name: commit sign
on:
  workflow_dispatch:
  push:

permissions: read-all

jobs:
  Create-Repo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Write GitHub context to log
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - run: echo "" >> README.md && echo ${{ github.sha }} >> README.md
      
      - name: push to git repo
        run: |
          git config --global user.name 'josh-terraform-app[bot]'
          git config --global user.email '145150012+josh-terraform-app[bot]@users.noreply.github.com'
          git add .
          git commit -m "updating readme"
          git push
